name: 'Call Claude API'
description: 'Generate SABSA artifacts using Anthropic Claude'

inputs:
  prompt:
    description: 'Assembled prompt text'
    required: true
  anthropic-api-key:
    description: 'Anthropic API key'
    required: true
  max-retries:
    description: 'Maximum retry attempts on failure'
    required: false
    default: '2'
  expected-sections:
    description: 'JSON array of expected section IDs'
    required: true

outputs:
  result:
    description: 'Parsed JSON response'
  success:
    description: 'Whether generation fully succeeded'
  error-message:
    description: 'Error details if failed'
  partial-result:
    description: 'Parseable content if partial failure'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        npm install --production

    - name: Run Claude action
      shell: bash
      env:
        INPUT_PROMPT: ${{ inputs.prompt }}
        INPUT_ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
        INPUT_MAX_RETRIES: ${{ inputs.max-retries }}
        INPUT_EXPECTED_SECTIONS: ${{ inputs.expected-sections }}
      run: |
        cd ${{ github.action_path }}
        node index.js
